/**
 * Centralized Mock Data for Custody Management System
 * Provides comprehensive realistic demo data for development and testing
 * All mock data is centralized here and accessed through API-like functions
 */

import type {
  User,
  UserRole,
  Wallet,
  Transaction,
  Analytics,
  ActivityItem,
  Notification,
  Report,
  ApprovalWorkflow,
  SystemSettings,
  TeamMember,
} from '@/types'

// ============================================================================
// USERS DATA
// ============================================================================

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@company.com',
    name: 'John Doe',
    role: 'admin' as UserRole,
    avatar: '/avatars/john-doe.jpg',
    phone: '+1 (555) 123-4567',
    department: 'Treasury',
    status: 'active',
    lastLogin: '2024-03-15T10:30:00Z',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-15T10:30:00Z',
    isActive: true,
    permissions: ['*'], // Admin has all permissions
    preferences: {
      theme: 'light',
      language: 'en',
      timezone: 'America/New_York',
      notifications: {
        email: true,
        push: true,
        sms: false,
      },
    },
  },
  {
    id: 'user-2',
    email: 'jane.smith@company.com',
    name: 'Jane Smith',
    role: 'manager' as UserRole,
    avatar: '/avatars/jane-smith.jpg',
    phone: '+1 (555) 234-5678',
    department: 'Operations',
    status: 'active',
    lastLogin: '2024-03-15T09:15:00Z',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-03-15T09:15:00Z',
    isActive: true,
    permissions: ['approve_transactions', 'view_wallets', 'create_transactions'],
    preferences: {
      theme: 'dark',
      language: 'en',
      timezone: 'America/New_York',
      notifications: {
        email: true,
        push: true,
        sms: true,
      },
    },
  },
  {
    id: 'user-3',
    email: 'mike.wilson@company.com',
    name: 'Mike Wilson',
    role: 'officer' as UserRole,
    avatar: '/avatars/mike-wilson.jpg',
    phone: '+1 (555) 345-6789',
    department: 'Trading',
    status: 'active',
    lastLogin: '2024-03-15T11:45:00Z',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-03-15T11:45:00Z',
    isActive: true,
    permissions: ['create_transactions', 'view_wallets', 'view_transactions'],
    preferences: {
      theme: 'light',
      language: 'en',
      timezone: 'America/Los_Angeles',
      notifications: {
        email: true,
        push: false,
        sms: false,
      },
    },
  },
  {
    id: 'user-4',
    email: 'emily.rodriguez@company.com',
    name: 'Emily Rodriguez',
    role: 'manager' as UserRole,
    avatar: '/avatars/emily-rodriguez.jpg',
    phone: '+1 (555) 456-7890',
    department: 'Compliance',
    status: 'active',
    lastLogin: '2024-03-15T13:20:00Z',
    createdAt: '2024-01-25T08:00:00Z',
    updatedAt: '2024-03-15T13:20:00Z',
    isActive: true,
    permissions: ['approve_transactions', 'view_transactions', 'view_wallets', 'generate_reports'],
    preferences: {
      theme: 'light',
      language: 'en',
      timezone: 'America/New_York',
      notifications: {
        email: true,
        push: true,
        sms: true,
      },
    },
  },
  {
    id: 'user-5',
    email: 'david.kim@company.com',
    name: 'David Kim',
    role: 'viewer' as UserRole,
    avatar: '/avatars/david-kim.jpg',
    phone: '+1 (555) 567-8901',
    department: 'Analytics',
    status: 'active',
    lastLogin: '2024-03-15T11:30:00Z',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-03-15T11:30:00Z',
    isActive: true,
    permissions: ['view_analytics', 'view_transactions', 'view_wallets', 'generate_reports'],
    preferences: {
      theme: 'dark',
      language: 'en',
      timezone: 'America/Los_Angeles',
      notifications: {
        email: true,
        push: false,
        sms: false,
      },
    },
  },
  {
    id: 'user-6',
    email: 'lisa.thompson@company.com',
    name: 'Lisa Thompson',
    role: 'officer' as UserRole,
    avatar: '/avatars/lisa-thompson.jpg',
    phone: '+1 (555) 678-9012',
    department: 'Operations',
    status: 'inactive',
    lastLogin: '2024-03-10T16:45:00Z',
    createdAt: '2024-01-30T08:00:00Z',
    updatedAt: '2024-03-10T16:45:00Z',
    isActive: false,
    permissions: ['create_transactions', 'view_wallets'],
    preferences: {
      theme: 'light',
      language: 'en',
      timezone: 'America/New_York',
      notifications: {
        email: false,
        push: false,
        sms: false,
      },
    },
  },
]

// ============================================================================
// WALLETS DATA
// ============================================================================

export const MOCK_WALLETS: Wallet[] = [
  {
    id: 'wallet-1',
    name: 'Main Treasury Wallet',
    address: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    currency: 'BTC',
    balance: 15.75432,
    usdValue: 1048320.50,
    status: 'active',
    type: 'hot',
    network: 'mainnet',
    description: 'Primary Bitcoin treasury wallet for daily operations',
    tags: ['treasury', 'primary'],
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-15T10:30:00Z',
    lastActivity: '2024-03-15T09:45:00Z',
    owner: 'user-1',
    approvers: ['user-1', 'user-2'],
    threshold: 2,
    isActive: true,
    metadata: {
      provider: 'Internal',
      derivationPath: "m/44'/0'/0'/0/0",
      publicKey: '02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 1247,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-2',
    name: 'Ethereum Operations',
    address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
    currency: 'ETH',
    balance: 245.8932,
    usdValue: 612233.00,
    status: 'active',
    type: 'hot',
    network: 'ethereum',
    description: 'Ethereum wallet for smart contract operations',
    tags: ['operations', 'smart-contracts'],
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-03-15T11:15:00Z',
    lastActivity: '2024-03-15T11:15:00Z',
    owner: 'user-2',
    approvers: ['user-1', 'user-2', 'user-4'],
    threshold: 2,
    isActive: true,
    metadata: {
      provider: 'MetaMask',
      derivationPath: "m/44'/60'/0'/0/0",
      publicKey: '0x04f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 892,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-3',
    name: 'USDT Operations',
    address: '0x8ba1f109551bD432803012645Hac136c22C501e',
    currency: 'USDT',
    balance: 2500000.00,
    usdValue: 2500000.00,
    status: 'active',
    type: 'hot',
    network: 'ethereum',
    description: 'Operational wallet for USDT transactions',
    tags: ['reserve', 'stablecoin'],
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-14T16:20:00Z',
    lastActivity: '2024-03-15T12:10:00Z',
    owner: 'user-1',
    approvers: ['user-1', 'user-2', 'user-4'],
    threshold: 3,
    isActive: true,
    metadata: {
      provider: 'Ledger',
      derivationPath: "m/44'/60'/0'/0/1",
      publicKey: '0x05f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 3456,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-4',
    name: 'Trading Wallet',
    address: '3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy',
    currency: 'BTC',
    balance: 8.25,
    usdValue: 548750.00,
    status: 'active',
    type: 'hot',
    network: 'mainnet',
    description: 'Bitcoin wallet for trading activities',
    tags: ['trading', 'active'],
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-03-15T12:30:00Z',
    lastActivity: '2024-03-15T12:30:00Z',
    owner: 'user-3',
    approvers: ['user-1', 'user-3'],
    threshold: 1,
    isActive: true,
    metadata: {
      provider: 'Internal',
      derivationPath: "m/44'/0'/0'/0/1",
      publicKey: '03f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 2134,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-5',
    name: 'Emergency Fund',
    address: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    currency: 'ETH',
    balance: 100.0,
    usdValue: 249000.00,
    status: 'frozen',
    type: 'cold',
    network: 'ethereum',
    description: 'Emergency fund wallet - requires special approval',
    tags: ['emergency', 'locked'],
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
    lastActivity: '2024-02-15T10:00:00Z',
    owner: 'user-1',
    approvers: ['user-1', 'user-4'],
    threshold: 2,
    isActive: true,
    metadata: {
      provider: 'Trezor',
      derivationPath: "m/44'/60'/0'/0/2",
      publicKey: '0x06f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 45,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-6',
    name: 'Polygon DeFi Wallet',
    address: '0x9f8f72aA9304c8B593d555F12eF6589cC3A579A2',
    currency: 'MATIC',
    balance: 25000.0,
    usdValue: 22500.00,
    status: 'active',
    type: 'hot',
    network: 'polygon',
    description: 'Polygon wallet for DeFi operations and yield farming',
    tags: ['defi', 'polygon', 'yield'],
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-03-15T14:20:00Z',
    lastActivity: '2024-03-15T14:20:00Z',
    owner: 'user-3',
    approvers: ['user-1', 'user-2', 'user-3'],
    threshold: 2,
    isActive: true,
    metadata: {
      provider: 'WalletConnect',
      derivationPath: "m/44'/966'/0'/0/0",
      publicKey: '0x07f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 567,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-7',
    name: 'Solana Treasury',
    address: 'DRpbCBMxVnDK7maPM5tGv6MvB3v1sRMC7Twn6dqNnqxR',
    currency: 'SOL',
    balance: 1500.0,
    usdValue: 135000.00,
    status: 'active',
    type: 'hot',
    network: 'solana',
    description: 'Solana wallet for ecosystem investments and staking',
    tags: ['solana', 'staking', 'ecosystem'],
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-03-15T16:45:00Z',
    lastActivity: '2024-03-15T16:45:00Z',
    owner: 'user-2',
    approvers: ['user-1', 'user-2'],
    threshold: 2,
    isActive: true,
    metadata: {
      provider: 'Phantom',
      derivationPath: "m/44'/501'/0'/0'",
      publicKey: 'DRpbCBMxVnDK7maPM5tGv6MvB3v1sRMC7Twn6dqNnqxR',
    },
    transactions: 234,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
  {
    id: 'wallet-8',
    name: 'Testnet Development',
    address: 'tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4',
    currency: 'BTC',
    balance: 0.5,
    usdValue: 0.00,
    status: 'active',
    type: 'hot',
    network: 'testnet',
    description: 'Bitcoin testnet wallet for development and testing',
    tags: ['testnet', 'development', 'testing'],
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-15T18:30:00Z',
    lastActivity: '2024-03-15T18:30:00Z',
    owner: 'user-3',
    approvers: ['user-3'],
    threshold: 1,
    isActive: true,
    metadata: {
      provider: 'Internal',
      derivationPath: "m/44'/1'/0'/0/0",
      publicKey: '04f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9',
    },
    transactions: 12,
    qrCode: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PC9zdmc+',
  },
];

// ============================================================================
// TRANSACTIONS DATA
// ============================================================================

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'send',
    status: 'pending',
    amount: 2.5,
    currency: 'BTC',
    usdValue: 162500.00,
    fromWallet: 'wallet-1',
    fromAddress: '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    toAddress: '3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy',
    fee: 0.0001,
    feeUsd: 6.50,
    txHash: '',
    blockHeight: null,
    confirmations: 0,
    requiredApprovals: 2,
    currentApprovals: 1,
    approvers: [
      { userId: 'user-1', status: 'approved', timestamp: '2024-03-15T14:30:00Z', comment: 'Approved for legitimate business transaction' },
      { userId: 'user-2', status: 'pending', timestamp: null, comment: null },
    ],
    createdBy: 'user-3',
    createdAt: '2024-03-15T14:25:00Z',
    updatedAt: '2024-03-15T14:30:00Z',
    description: 'Payment to vendor for services',
    tags: ['vendor-payment', 'operations'],
    priority: 'medium',
  },
  {
    id: 'tx-2',
    type: 'receive',
    status: 'completed',
    amount: 50.0,
    currency: 'ETH',
    usdValue: 172500.00,
    fromAddress: '0x8ba1f109551bD432803012645Hac136c22C501e',
    toWallet: 'wallet-2',
    toAddress: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
    fee: 0.002,
    feeUsd: 6.90,
    txHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    blockHeight: 19456789,
    confirmations: 25,
    requiredApprovals: 0,
    currentApprovals: 0,
    approvers: [],
    createdBy: 'system',
    createdAt: '2024-03-14T16:20:00Z',
    updatedAt: '2024-03-14T16:45:00Z',
    description: 'Incoming payment from client',
    tags: ['client-payment', 'revenue'],
    priority: 'low',
  },
  {
    id: 'tx-3',
    type: 'send',
    status: 'approved',
    amount: 100000.0,
    currency: 'USDT',
    usdValue: 100000.00,
    fromWallet: 'wallet-3',
    fromAddress: '0x8ba1f109551bD432803012645Hac136c22C501e',
    toAddress: '0x9876543210fedcba9876543210fedcba98765432',
    fee: 5.0,
    feeUsd: 5.0,
    txHash: '',
    blockHeight: null,
    confirmations: 0,
    requiredApprovals: 3,
    currentApprovals: 3,
    approvers: [
      { userId: 'user-1', status: 'approved', timestamp: '2024-03-15T10:30:00Z', comment: 'Large transaction approved' },
      { userId: 'user-2', status: 'approved', timestamp: '2024-03-15T11:15:00Z', comment: 'Verified and approved' },
      { userId: 'user-4', status: 'approved', timestamp: '2024-03-15T11:45:00Z', comment: 'Final approval granted' },
    ],
    createdBy: 'user-3',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-03-15T11:45:00Z',
    description: 'Large transfer to exchange for trading',
    tags: ['exchange-transfer', 'trading'],
    priority: 'high',
  },
  {
    id: 'tx-4',
    type: 'send',
    status: 'rejected',
    amount: 1000.0,
    currency: 'BNB',
    usdValue: 440000.00,
    fromWallet: 'wallet-4',
    fromAddress: 'bnb1grpf0955h0ykzq3ar5nmum7y6gdfl6lxfn46h2',
    toAddress: 'bnb1xyz123abc456def789ghi012jkl345mno678pqr',
    fee: 0.1,
    feeUsd: 44.00,
    txHash: '',
    blockHeight: null,
    confirmations: 0,
    requiredApprovals: 2,
    currentApprovals: 1,
    approvers: [
      { userId: 'user-1', status: 'rejected', timestamp: '2024-03-15T09:30:00Z', comment: 'Insufficient documentation provided' },
      { userId: 'user-2', status: 'pending', timestamp: null, comment: null },
    ],
    createdBy: 'user-3',
    createdAt: '2024-03-15T09:00:00Z',
    updatedAt: '2024-03-15T09:30:00Z',
    description: 'Transfer to new partner wallet',
    tags: ['partner-transfer', 'new-relationship'],
    priority: 'medium',
  },
];

// ============================================================================
// ACTIVITIES DATA
// ============================================================================

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: 'activity-1',
    type: 'case_created',
    description: 'Large USDC transfer to partner exchange',
    userId: 'user-2',
    createdAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 'activity-2',
    type: 'case_updated',
    description: 'Bitcoin trading allocation approved',
    userId: 'user-1',
    createdAt: '2024-03-15T12:00:00Z',
  },
  {
    id: 'activity-3',
    type: 'case_closed',
    description: 'Emergency fund withdrawal rejected',
    userId: 'user-4',
    createdAt: '2024-03-15T13:30:00Z',
  },
  {
    id: 'activity-4',
    type: 'document_uploaded',
    description: 'Testnet development wallet created',
    userId: 'user-3',
    createdAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'activity-5',
    type: 'note_added',
    description: 'Successful login from new device',
    userId: 'user-2',
    createdAt: '2024-03-15T09:15:00Z',
  },
  {
    id: 'activity-6',
    type: 'status_changed',
    description: 'Multiple failed login attempts detected',
    userId: 'user-1',
    createdAt: '2024-03-14T22:30:00Z',
  },
  {
    id: 'activity-7',
    type: 'case_created',
    description: 'Staking rewards received',
    userId: 'user-2',
    createdAt: '2024-03-15T07:15:00Z',
  },
  {
    id: 'activity-8',
    type: 'case_updated',
    description: 'High-value transaction workflow modified',
    userId: 'user-1',
    createdAt: '2024-03-14T16:00:00Z',
  },
]

// ============================================================================
// ANALYTICS & DASHBOARD DATA
// ============================================================================

export const MOCK_ANALYTICS: Analytics = {
  portfolio: {
    totalValue: 3615320.50,
    totalAssets: 8,
    change24h: 85420.30,
    changePercent24h: 2.42,
    breakdown: [
      { currency: 'BTC', value: 1613070.50, percentage: 44.6, change24h: 1.8 },
      { currency: 'ETH', value: 861233.00, percentage: 23.8, change24h: 3.2 },
      { currency: 'USDC', value: 500000.00, percentage: 13.8, change24h: 0.1 },
      { currency: 'SOL', value: 135000.00, percentage: 3.7, change24h: 5.4 },
      { currency: 'ETH', value: 249000.00, percentage: 6.9, change24h: 2.1 },
      { currency: 'MATIC', value: 22500.00, percentage: 0.6, change24h: -1.2 },
      { currency: 'BTC', value: 0.00, percentage: 0.0, change24h: 0.0 },
    ],
  },
  transactions: {
    total: 2847,
    pending: 2,
    completed: 2840,
    failed: 1,
    rejected: 1,
    approved: 3,
    volume24h: 847392.45,
    volumeChange24h: 12.67,
    avgTransactionValue: 297.84,
    largestTransaction: 162500.00,
  },
  wallets: {
    total: 8,
    active: 7,
    inactive: 0,
    locked: 1,
    hot: 6,
    cold: 2,
  },
  security: {
    pendingApprovals: 2,
    failedLogins24h: 0,
    activeApiKeys: 3,
    lastSecurityAudit: '2024-03-10T08:00:00Z',
  },
  pendingActions: {
    approvals: 2,
    reviews: 1,
    alerts: 0,
    notifications: 5,
  },
  performance: {
    uptime: 99.98,
    avgResponseTime: 245,
    transactionSuccessRate: 99.65,
    systemLoad: 23.4,
  },
  recentActivity: MOCK_ACTIVITIES,
} as const;

// ============================================================================
// ACTIVITIES DATA
// ============================================================================

// ============================================================================
// APPROVAL WORKFLOWS DATA
// ============================================================================

export const MOCK_APPROVAL_WORKFLOWS: ApprovalWorkflow[] = [
  {
    id: 'workflow-1',
    name: 'High Value Transactions',
    description: 'Approval workflow for transactions over $50,000',
    rules: [
      {
        condition: 'amount > 50000',
        requiredApprovals: 2,
        approvers: ['user-1', 'user-2', 'user-4'] as readonly string[],
      },
    ],
    isActive: true,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'workflow-2',
    name: 'Emergency Fund Access',
    description: 'Special approval for emergency fund withdrawals',
    rules: [
      {
        condition: 'wallet_id == "wallet-5"',
        requiredApprovals: 2,
        approvers: ['user-1', 'user-4'] as readonly string[],
      },
    ],
    isActive: true,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'workflow-3',
    name: 'Standard Operations',
    description: 'Default approval workflow for regular transactions',
    rules: [
      {
        condition: 'amount <= 49999',
        requiredApprovals: 1,
        approvers: ['user-2', 'user-3'] as readonly string[],
      },
    ],
    isActive: true,
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-03-10T14:00:00Z',
  },
  {
    id: 'workflow-4',
    name: 'DeFi Operations',
    description: 'Approval workflow for DeFi and yield farming operations',
    rules: [
      {
        condition: 'amount >= 1000 && amount <= 100000 && wallet_id == "wallet-6"',
        requiredApprovals: 2,
        approvers: ['user-2', 'user-3'] as readonly string[],
      },
    ],
    isActive: true,
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-03-05T12:00:00Z',
  },
  {
    id: 'workflow-5',
    name: 'Testnet Operations',
    description: 'Simplified workflow for testnet transactions',
    rules: [
      {
        condition: 'wallet_id == "wallet-8"',
        requiredApprovals: 1,
        approvers: ['user-3'] as readonly string[],
      },
    ],
    isActive: true,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-01T08:00:00Z',
  },
] as const;

// Utility functions for mock data
export const getMockWalletById = (id: string) => {
  return MOCK_WALLETS.find(wallet => wallet.id === id);
};

export const getMockTransactionById = (id: string) => {
  return MOCK_TRANSACTIONS.find(transaction => transaction.id === id);
};

export const getMockUserById = (id: string) => {
  return MOCK_USERS.find(user => user.id === id);
};

export const getMockTransactionsByWallet = (walletId: string) => {
  return MOCK_TRANSACTIONS.filter(
    transaction => 
      (transaction.fromWallet === walletId) || 
      (transaction.toWallet === walletId)
  );
};

export const getMockPendingTransactions = () => {
  return MOCK_TRANSACTIONS.filter(transaction => transaction.status === 'pending');
};

export const getMockTransactionsByStatus = (status: string) => {
  return MOCK_TRANSACTIONS.filter(transaction => transaction.status === status);
};

// Mock Security Settings Data
export const MOCK_SECURITY_SETTINGS = {
  twoFactorAuth: {
    enabled: true,
    method: 'authenticator',
    backupCodes: 8,
    lastUsed: '2024-03-15T10:30:00Z',
  },
  apiKeys: [
    {
      id: 'api-1',
      name: 'Trading Bot API',
      key: 'ak_live_1234567890abcdef',
      permissions: ['read_wallets', 'create_transactions'],
      lastUsed: '2024-03-15T14:20:00Z',
      createdAt: '2024-02-01T08:00:00Z',
      status: 'active',
    },
    {
      id: 'api-2',
      name: 'Analytics Dashboard',
      key: 'ak_live_fedcba0987654321',
      permissions: ['read_wallets', 'read_transactions'],
      lastUsed: '2024-03-14T16:45:00Z',
      createdAt: '2024-01-15T08:00:00Z',
      status: 'active',
    },
  ],
  ipWhitelist: {
    enabled: true,
    addresses: [
      '192.168.1.100',
      '10.0.0.50',
      '203.0.113.10'
    ]
  },
  loginSessions: [
    {
      id: 'session-1',
      userId: 'user-1',
      device: 'MacBook Pro - Chrome',
      deviceType: 'desktop',
      location: 'San Francisco, CA',
      ipAddress: '192.168.1.100',
      loginTime: '2024-03-15T08:00:00Z',
      startTime: '2024-03-15T08:00:00Z',
      lastActivity: '2024-03-15T14:30:00Z',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
      status: 'active',
      current: true,
    },
    {
      id: 'session-2',
      userId: 'user-1',
      device: 'iPhone 15 Pro - Safari',
      deviceType: 'mobile',
      location: 'San Francisco, CA',
      ipAddress: '192.168.1.101',
      loginTime: '2024-03-14T18:30:00Z',
      startTime: '2024-03-14T18:30:00Z',
      lastActivity: '2024-03-14T22:15:00Z',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15',
      status: 'expired',
      current: false,
    },
  ],
  activeSessions: [
    {
      id: 'session-1',
      userId: 'user-1',
      device: 'MacBook Pro - Chrome',
      deviceType: 'desktop',
      location: 'San Francisco, CA',
      ipAddress: '192.168.1.100',
      loginTime: '2024-03-15T08:00:00Z',
      startTime: '2024-03-15T08:00:00Z',
      lastActivity: '2024-03-15T14:30:00Z',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
      status: 'active',
      current: true,
    },
    {
      id: 'session-2',
      userId: 'user-1',
      device: 'iPhone 15 Pro - Safari',
      deviceType: 'mobile',
      location: 'San Francisco, CA',
      ipAddress: '192.168.1.101',
      loginTime: '2024-03-14T18:30:00Z',
      startTime: '2024-03-14T18:30:00Z',
      lastActivity: '2024-03-14T22:15:00Z',
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15',
      status: 'expired',
      current: false,
    },
  ],
  auditLogs: [
    {
      id: 'audit-1',
      action: 'transaction_created',
      details: 'Created transaction tx-1 for 2.5 BTC',
      userId: '3',
      userName: 'Michael Chen',
      timestamp: '2024-03-15T14:25:00Z',
      ipAddress: '192.168.1.100',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'success',
      resource: 'Transaction',
    },
    {
      id: 'audit-2',
      action: 'transaction_approved',
      details: 'Approved transaction tx-3 for 100,000 USDT',
      userId: '1',
      userName: 'John Smith',
      timestamp: '2024-03-15T10:30:00Z',
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'success',
      resource: 'Transaction',
    },
    {
      id: 'audit-3',
      action: 'wallet_created',
      details: 'Created new wallet: BNB Trading Wallet',
      userId: '1',
      userName: 'John Smith',
      timestamp: '2024-03-15T10:30:00Z',
      ipAddress: '192.168.1.102',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      status: 'success',
      resource: 'Wallet',
    },
  ],
} as const;

// ============================================================================
// MOCK NOTIFICATIONS
// ============================================================================
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    title: 'High Value Transaction Pending',
    message: 'Transaction TX-001 (0.5 BTC - $32,500) requires your approval',
    type: 'info',
    read: false,
    userId: 'user-1',
    createdAt: '2024-03-15T14:30:00Z',
  },
  {
    id: 'notif-2',
    title: 'New Multi-Sig Wallet Created',
    message: 'Multi-signature wallet "DeFi Operations" has been successfully created',
    type: 'info',
    read: true,
    userId: 'user-2',
    createdAt: '2024-03-14T15:20:00Z',
  },
  {
    id: 'notif-3',
    title: 'Security Alert: Suspicious Login',
    message: 'Failed login attempt detected from IP 192.168.1.100 (Unknown Location)',
    type: 'warning',
    read: false,
    userId: 'user-1',
    createdAt: '2024-03-15T09:15:00Z',
  },
  {
    id: 'notif-4',
    title: 'Transaction Completed Successfully',
    message: 'Your Bitcoin transfer of 0.5 BTC to Binance has been completed',
    type: 'success',
    read: true,
    userId: 'user-3',
    createdAt: '2024-03-13T14:45:00Z',
  },
  {
    id: 'notif-5',
    title: 'Wallet Balance Low',
    message: 'Hot Wallet balance is below threshold (< 1 ETH)',
    type: 'warning',
    read: false,
    userId: 'user-2',
    createdAt: '2024-03-15T08:00:00Z',
  },
  {
    id: 'notif-6',
    title: 'API Key Expires Soon',
    message: 'Your API key "Trading Bot Key" will expire in 7 days',
    type: 'warning',
    read: false,
    userId: 'user-3',
    createdAt: '2024-03-15T06:00:00Z',
  },
  {
    id: 'notif-7',
    title: 'DeFi Yield Harvested',
    message: 'Successfully harvested 125.5 MATIC from Polygon staking rewards',
    type: 'success',
    read: true,
    userId: 'user-3',
    createdAt: '2024-03-12T12:00:00Z',
  },
  {
    id: 'notif-8',
    title: 'Compliance Review Required',
    message: 'Monthly compliance review is due for all high-value wallets',
    type: 'info',
    read: false,
    userId: 'user-4',
    createdAt: '2024-03-14T09:00:00Z',
  },
];

// ============================================================================
// MOCK REPORTS
// ============================================================================
export const MOCK_REPORTS: Report[] = [
  {
    id: 'report-1',
    name: 'Monthly Transaction Report - March 2024',
    description: 'Comprehensive transaction analysis including volume, fees, and approval metrics',
    type: 'transaction',
    status: 'completed',
    generatedAt: '2024-03-01T00:00:00Z',
    size: '2.5 MB',
    format: 'pdf',
  },
  {
    id: 'report-2',
    name: 'Q1 2024 Security Audit Report',
    description: 'Quarterly security audit covering access logs, failed attempts, and compliance review',
    type: 'security',
    status: 'generating',
    generatedAt: '2024-03-15T14:30:00Z',
    size: '1.8 MB',
    format: 'pdf',
  },
  {
    id: 'report-3',
    name: 'Portfolio Performance Analysis - February 2024',
    description: 'Asset allocation, performance metrics, and risk analysis across all managed wallets',
    type: 'portfolio',
    status: 'completed',
    generatedAt: '2024-02-28T23:59:59Z',
    size: '1.8 MB',
    format: 'excel',
  },
  {
    id: 'report-4',
    name: 'DeFi Operations Summary - Q1 2024',
    description: 'Comprehensive analysis of DeFi activities, yields, and protocol interactions',
    type: 'defi',
    status: 'completed',
    generatedAt: '2024-03-10T12:00:00Z',
    size: '3.2 MB',
    format: 'pdf',
  },
  {
    id: 'report-5',
    name: 'Compliance Report - AML/KYC Review',
    description: 'Anti-Money Laundering and Know Your Customer compliance review',
    type: 'compliance',
    status: 'pending',
    generatedAt: '2024-03-15T08:00:00Z',
    size: '2.1 MB',
    format: 'pdf',
  },
  {
    id: 'report-6',
    name: 'Gas Fee Analysis - March 2024',
    description: 'Analysis of gas fees across different networks and optimization recommendations',
    type: 'analytics',
    status: 'completed',
    generatedAt: '2024-03-12T16:00:00Z',
    size: '950 KB',
    format: 'excel',
  },
];

// ============================================================================
// MOCK SYSTEM SETTINGS
// ============================================================================
export const MOCK_SYSTEM_SETTINGS: SystemSettings = {
  general: {
    siteName: 'Custody Management System',
    siteDescription: 'Enterprise-grade digital asset custody and management platform',
    version: '2.1.4',
    environment: 'production',
    timezone: 'UTC',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '24h',
    language: 'en',
    currency: 'USD',
    maintenanceMode: false,
    debugMode: false,
    logoUrl: '/assets/logo.svg',
    faviconUrl: '/assets/favicon.ico',
    supportEmail: 'support@custody.com',
    supportPhone: '+1-800-CUSTODY',
    companyName: 'Custody Solutions Inc.',
    companyAddress: '123 Financial District, New York, NY 10004',
  },
  security: {
    sessionTimeout: 3600, // 1 hour in seconds
    maxLoginAttempts: 5,
    lockoutDuration: 900, // 15 minutes in seconds
    passwordMinLength: 12,
    passwordMaxLength: 128,
    passwordRequireSpecialChars: true,
    passwordRequireNumbers: true,
    passwordRequireUppercase: true,
    passwordRequireLowercase: true,
    passwordExpiryDays: 90,
    passwordHistoryCount: 12,
    twoFactorRequired: true,
    twoFactorMethods: ['totp', 'sms', 'email'],
    ipWhitelistEnabled: false,
    allowedIPs: [],
    apiKeyExpiryDays: 365,
    maxApiKeysPerUser: 10,
    encryptionAlgorithm: 'AES-256-GCM',
    hashingAlgorithm: 'bcrypt',
    saltRounds: 12,
    jwtExpiryHours: 24,
    refreshTokenExpiryDays: 30,
    auditLogRetentionDays: 2555, // 7 years
    securityHeaders: {
      hsts: true,
      csp: true,
      xssProtection: true,
      frameOptions: 'DENY',
      contentTypeOptions: true,
    },
  },
  notifications: {
    emailEnabled: true,
    smsEnabled: true,
    pushEnabled: true,
    slackEnabled: false,
    webhookEnabled: true,
    telegramEnabled: false,
    emailSettings: {
      provider: 'sendgrid',
      smtpHost: 'smtp.sendgrid.net',
      smtpPort: 587,
      smtpUser: 'apikey',
      smtpPassword: '***',
      fromEmail: 'noreply@custody.com',
      fromName: 'Custody Management',
      replyToEmail: 'support@custody.com',
      maxRetries: 3,
      retryDelay: 5000,
      // Notification preferences
      transactionAlerts: true,
      securityAlerts: true,
      systemUpdates: false,
      dailyReports: true,
    },
    smsSettings: {
      provider: 'twilio',
      accountSid: '***',
      authToken: '***',
      fromNumber: '+1234567890',
      maxRetries: 3,
    },
    pushSettings: {
      provider: 'firebase',
      serverKey: '***',
      vapidKey: '***',
      // Notification preferences
      approvalRequests: true,
      lowBalanceAlerts: true,
      failedTransactions: true,
      systemMaintenance: false,
    },
    webhookSettings: {
      maxRetries: 5,
      retryDelay: 10000,
      timeout: 30000,
      signatureSecret: '***',
    },
    defaultChannels: {
      transactionCreated: ['email', 'push'],
      transactionApproved: ['email', 'push'],
      transactionRejected: ['email', 'push', 'sms'],
      securityAlert: ['email', 'sms', 'push'],
      walletCreated: ['email'],
      lowBalance: ['email', 'push'],
      systemMaintenance: ['email'],
    },
  },
  limits: {
    maxWalletsPerUser: 50,
    maxTransactionAmount: 10000000, // $10M
    dailyTransactionLimit: 50000000, // $50M
    monthlyTransactionLimit: 500000000, // $500M
    maxPendingTransactions: 100,
    maxApproversPerWorkflow: 10,
    maxWorkflowSteps: 5,
    apiRateLimit: 1000, // requests per hour
    apiRateLimitWindow: 3600, // 1 hour in seconds
    maxApiRequestSize: 10485760, // 10MB
    maxFileUploadSize: 52428800, // 50MB
    maxReportRetentionDays: 2555, // 7 years
  },
};

// ============================================================================
// MOCK TEAM MEMBERS DATA
// ============================================================================
export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  // Existing users with enhanced team member data
  {
    id: 'user-1',
    name: 'John Smith',
    email: 'john.smith@company.com',
    role: 'admin',
    status: 'active',
    avatar: '/avatars/john-smith.jpg',
    department: 'IT Security',
    lastLogin: '2024-03-15T14:30:00Z',
    permissions: ['all'],
    createdAt: '2024-01-15T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-001',
    position: 'Chief Security Officer',
    level: 'executive',
    salary: {
      amount: 180000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Cybersecurity', 'Risk Management', 'Blockchain Security', 'Team Leadership'],
    certifications: ['CISSP', 'CISM', 'CEH'],
    workLocation: 'New York, NY',
    reportingTo: null,
    directReports: ['user-2', 'user-3'],
    emergencyContact: {
      name: 'Jane Smith',
      relationship: 'Spouse',
      phone: '+1-555-0101',
      email: 'jane.smith@email.com',
    },
    workSchedule: {
      type: 'full-time',
      hoursPerWeek: 40,
      workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      startTime: '09:00',
      endTime: '17:00',
      timezone: 'America/New_York',
    },
    performance: {
      lastReviewDate: '2024-01-15T00:00:00Z',
      nextReviewDate: '2025-01-15T00:00:00Z',
      rating: 'excellent',
      goals: ['Implement zero-trust security', 'Reduce security incidents by 50%'],
      achievements: ['Led successful security audit', 'Implemented MFA system'],
    },
    benefits: {
      healthInsurance: true,
      dentalInsurance: true,
      visionInsurance: true,
      retirement401k: true,
      paidTimeOff: 25,
      sickLeave: 10,
      stockOptions: true,
    },
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'approver',
    status: 'active',
    avatar: '/avatars/sarah-johnson.jpg',
    department: 'Finance',
    lastLogin: '2024-03-15T12:15:00Z',
    permissions: ['approve_transactions', 'view_wallets', 'generate_reports'],
    createdAt: '2024-01-20T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-002',
    position: 'Senior Financial Analyst',
    level: 'senior',
    salary: {
      amount: 95000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Financial Analysis', 'Risk Assessment', 'Cryptocurrency', 'Excel'],
    certifications: ['CFA', 'FRM'],
    workLocation: 'Remote',
    reportingTo: 'user-1',
    directReports: [],
    emergencyContact: {
      name: 'Michael Johnson',
      relationship: 'Brother',
      phone: '+1-555-0102',
      email: 'michael.johnson@email.com',
    },
    workSchedule: {
      type: 'full-time',
      hoursPerWeek: 40,
      workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      startTime: '08:00',
      endTime: '16:00',
      timezone: 'America/Chicago',
    },
    performance: {
      lastReviewDate: '2024-02-01T00:00:00Z',
      nextReviewDate: '2025-02-01T00:00:00Z',
      rating: 'excellent',
      goals: ['Improve transaction approval time', 'Develop new risk models'],
      achievements: ['Reduced approval time by 30%', 'Identified $2M in cost savings'],
    },
    benefits: {
      healthInsurance: true,
      dentalInsurance: true,
      visionInsurance: false,
      retirement401k: true,
      paidTimeOff: 20,
      sickLeave: 8,
      stockOptions: false,
    },
  },
  {
    id: 'user-3',
    name: 'Mike Wilson',
    email: 'mike.wilson@company.com',
    role: 'viewer',
    status: 'active',
    avatar: '/avatars/mike-wilson.jpg',
    department: 'Operations',
    lastLogin: '2024-03-15T09:45:00Z',
    permissions: ['view_transactions', 'view_wallets'],
    createdAt: '2024-02-01T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-003',
    position: 'Operations Specialist',
    level: 'mid',
    salary: {
      amount: 65000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Operations Management', 'Process Improvement', 'Data Analysis'],
    certifications: ['Six Sigma Green Belt'],
    workLocation: 'San Francisco, CA',
    reportingTo: 'user-1',
    directReports: [],
    emergencyContact: {
      name: 'Lisa Wilson',
      relationship: 'Wife',
      phone: '+1-555-0103',
      email: 'lisa.wilson@email.com',
    },
    workSchedule: {
      type: 'full-time',
      hoursPerWeek: 40,
      workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      startTime: '09:00',
      endTime: '17:00',
      timezone: 'America/Los_Angeles',
    },
    performance: {
      lastReviewDate: '2024-02-15T00:00:00Z',
      nextReviewDate: '2025-02-15T00:00:00Z',
      rating: 'good',
      goals: ['Streamline operations processes', 'Complete advanced training'],
      achievements: ['Improved process efficiency by 15%', 'Zero operational errors'],
    },
    benefits: {
      healthInsurance: true,
      dentalInsurance: true,
      visionInsurance: true,
      retirement401k: true,
      paidTimeOff: 15,
      sickLeave: 8,
      stockOptions: false,
    },
  },
  // Additional team members
  {
    id: 'user-4',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    role: 'compliance',
    status: 'active',
    avatar: '/avatars/emily-rodriguez.jpg',
    department: 'Compliance',
    lastLogin: '2024-03-15T13:20:00Z',
    permissions: ['view_transactions', 'flag_transactions', 'generate_reports'],
    createdAt: '2024-01-25T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-004',
    position: 'Compliance Manager',
    level: 'senior',
    salary: {
      amount: 105000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Regulatory Compliance', 'AML/KYC', 'Legal Research', 'Audit Management'],
    certifications: ['CAMS', 'ACAMS', 'Series 7'],
    workLocation: 'Chicago, IL',
    reportingTo: 'user-1',
    directReports: ['user-6'],
    emergencyContact: {
      name: 'Carlos Rodriguez',
      relationship: 'Husband',
      phone: '+1-555-0104',
      email: 'carlos.rodriguez@email.com',
    },
    workSchedule: {
      type: 'full-time',
      hoursPerWeek: 40,
      workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      startTime: '08:30',
      endTime: '16:30',
      timezone: 'America/Chicago',
    },
    performance: {
      lastReviewDate: '2024-01-30T00:00:00Z',
      nextReviewDate: '2025-01-30T00:00:00Z',
      rating: 'excellent',
      goals: ['Implement new compliance framework', 'Reduce compliance violations'],
      achievements: ['Zero regulatory violations', 'Streamlined KYC process'],
    },
    benefits: {
      healthInsurance: true,
      dentalInsurance: true,
      visionInsurance: true,
      retirement401k: true,
      paidTimeOff: 22,
      sickLeave: 10,
      stockOptions: true,
    },
  },
  {
    id: 'user-5',
    name: 'David Kim',
    email: 'david.kim@company.com',
    role: 'analyst',
    status: 'active',
    avatar: '/avatars/david-kim.jpg',
    department: 'Analytics',
    lastLogin: '2024-03-15T11:30:00Z',
    permissions: ['view_analytics', 'generate_reports'],
    createdAt: '2024-02-10T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-005',
    position: 'Data Analyst',
    level: 'mid',
    salary: {
      amount: 75000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Data Analysis', 'Python', 'SQL', 'Machine Learning', 'Tableau'],
    certifications: ['Google Analytics', 'Tableau Desktop Specialist'],
    workLocation: 'Austin, TX',
    reportingTo: 'user-2',
    directReports: [],
    emergencyContact: {
      name: 'Jennifer Kim',
      relationship: 'Sister',
      phone: '+1-555-0105',
      email: 'jennifer.kim@email.com',
    },
    workSchedule: {
      type: 'full-time',
      hoursPerWeek: 40,
      workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      startTime: '09:00',
      endTime: '17:00',
      timezone: 'America/Chicago',
    },
    performance: {
      lastReviewDate: '2024-02-20T00:00:00Z',
      nextReviewDate: '2025-02-20T00:00:00Z',
      rating: 'excellent',
      goals: ['Develop predictive models', 'Automate reporting processes'],
      achievements: ['Built fraud detection model', 'Reduced report generation time by 60%'],
    },
    benefits: {
      healthInsurance: true,
      dentalInsurance: true,
      visionInsurance: false,
      retirement401k: true,
      paidTimeOff: 18,
      sickLeave: 8,
      stockOptions: false,
    },
  },
  {
    id: 'user-6',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    role: 'operator',
    status: 'inactive',
    avatar: '/avatars/lisa-thompson.jpg',
    department: 'Operations',
    lastLogin: '2024-03-10T16:45:00Z',
    permissions: ['create_transactions', 'view_wallets'],
    createdAt: '2024-01-30T08:00:00Z',
    // Enhanced team member fields
    employeeId: 'EMP-006',
    position: 'Junior Operations Analyst',
    level: 'junior',
    salary: {
      amount: 55000,
      currency: 'USD',
      frequency: 'annual',
    },
    skills: ['Transaction Processing', 'Customer Service', 'Documentation'],
    certifications: ['CompTIA Security+'],
    workLocation: 'Remote',
    reportingTo: 'user-4',
    directReports: [],
    emergencyContact: {
      name: 'Robert Thompson',
      relationship: 'Father',
      phone: '+1-555-0106',
      email: 'robert.thompson@email.com',
    },
    workSchedule: {
      type: 'part-time',
      hoursPerWeek: 20,
      workDays: ['monday', 'wednesday', 'friday'],
      startTime: '10:00',
      endTime: '16:00',
      timezone: 'America/Eastern',
    },
    performance: {
      lastReviewDate: '2024-02-05T00:00:00Z',
      nextReviewDate: '2025-02-05T00:00:00Z',
      rating: 'good',
      goals: ['Complete certification training', 'Improve processing speed'],
      achievements: ['Completed onboarding program', 'Maintained 99% accuracy'],
    },
    benefits: {
      healthInsurance: false,
      dentalInsurance: false,
      visionInsurance: false,
      retirement401k: false,
      paidTimeOff: 10,
      sickLeave: 5,
      stockOptions: false,
    },
  },
];